# Generated by Django 4.0.1 on 2022-01-25 20:00

from django.db import migrations, models
import django.db.models.deletion
import slideshow.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSlideShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('is_deleted', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('group_slideshow', models.ForeignKey(on_delete=models.SET(slideshow.models.get_delete_slide_group), to='slideshow.groupslideshow')),
                ('link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('is_deleted', 'title')},
            },
        ),
    ]
