# Generated by Django 3.2.8 on 2021-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmenu',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
